version: "3.7"

volumes:
  postgres:

services:
  database:
    container_name: database
    build:
      postgres/
    ports:
      - 5431:5432
    volumes:
      - postgres:/var/lib/data/postgresql
    restart: on-failure

  spyer:
    depends_on:
      - database
    container_name: spyer
    build:
      .
    ports:
      - $SPYER_DEBUG_PORT:$SPYER_DEBUG_PORT
      - 8000:8000
    environment:
      SPYER_OPTS: $SPYER_OPTS
    restart: on-failure