server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: sberfood_orders
    open-in-view: false
  datasource:
    url: jdbc:p6spy:postgresql://database:5432/spyer
    username: admin
    password: admin
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: spyer_users
  liquibase:
    url: jdbc:postgresql://database:5432/spyer
    default-schema: spyer_users
    user: admin
    password: admin
    change-log: classpath:liquibase/changelog.yaml
    contexts: native
    enabled: true
